#----------------------------------------------------------------------------
# MonkOS libc makefile
#
# Makefile for the c library.
#----------------------------------------------------------------------------

DIR_ROOT	:= ..
LIB_NAME	:= libc
LIB_DEPS	:=
POST_LIB_RULE	:=

include $(DIR_ROOT)/scripts/lib.mk
