MonkOS: /home/brett/c/monk/include/kernel/debug/dump.h File Reference
dump.h File Reference
Debugging memory and CPU state dump routines.
#include <core.h>
#include <kernel/x86/cpu.h>
Enumerations
Functions
int dump_registers (char *buf, size_t bufsize, const registers_t *regs)
Dump the contents of a CPU registers structure to a string buffer.
int dump_cpuflags (char *buf, size_t bufsize, uint64_t rflags)
Dump the contents of the CPU flags register.
int dump_memory (char *buf, size_t bufsize, const void *mem, size_t memsize, enum dumpstyle style)
Dump the contents of memory.
Detailed Description
Debugging memory and CPU state dump routines.
Definition in file dump.h.
Enumeration Type Documentation
enum dumpstyle
Memory dump output style.
Used to select how the memory address is displayed in a a memory dump.
Enumerator
DUMPSTYLE_NOADDR
No address or offset in memory dump.
DUMPSTYLE_ADDR
Include full address in memory dump.
DUMPSTYLE_OFFSET
Include address offset in memory dump.
Definition at line 48 of file dump.h.
Function Documentation
int dump_registers (char * buf, size_t bufsize, const registers_t * regs)
Dump the contents of a CPU registers structure to a string buffer.
Parameters
[in] buf Pointer to the character buffer to hold the resulting null-terminated string.
[in] bufsize Size of the buffer used to hold the string.
[in] regs Pointer to a CPU registers structure.
Returns
The number of characters that would have been written to the buffer if n had been sufficiently large.
Definition at line 16 of file dump.c.
Referenced by dump_context().
int dump_cpuflags (char * buf, size_t bufsize, uint64_t rflags)
Dump the contents of the CPU flags register.
Parameters
[in] buf Pointer to the character buffer to hold the resulting null-terminated string.
[in] bufsize Size of the buffer used to hold the string.
[in] rflags The 64-bit rflags register value.
Returns
The number of characters that would have been written to the buffer if n had been sufficiently large.
Definition at line 33 of file dump.c.
Referenced by dump_context().
int dump_memory (char * buf, size_t bufsize, const void * mem, size_t memsize, enum dumpstyle style)
Dump the contents of memory.
Parameters
[in] buf Pointer to the character buffer to hold the resulting null-terminated string.
[in] bufsize Size of the buffer used to hold the string.
[in] mem Pointer to the first byte of memory to dump.
[in] memsize Number of memory bytes to dump.
[in] style The output style used for the memory dump.
Returns
The number of characters that would have been written to the buffer if n had been sufficiently large.
Definition at line 50 of file dump.c.
Referenced by dump_context().