MonkOS: /home/brett/c/monk/include/kernel/mem/heap.h File Reference
heap.h File Reference
A simple heap memory manager.
#include <core.h>
#include <kernel/mem/paging.h>
Functions
heap_t * heap_create (pagetable_t *pt, void *vaddr, uint64_t maxpages)
Create a new heap from which to allocate virtual memory.
void heap_destroy (heap_t *heap)
Destroy a heap, returning its memory to page table.
void * heap_alloc (heap_t *heap, uint64_t size)
Allocate memory from a heap.
void heap_free (heap_t *heap, void *ptr)
Free memory previously allocated with heap_alloc.
Detailed Description
A simple heap memory manager.
Definition in file heap.h.
Function Documentation
heap_t* heap_create (pagetable_t * pt, void * vaddr, uint64_t maxpages)
Create a new heap from which to allocate virtual memory.
Parameters
[in] pt The page table from which virtual memory is to be allocated.
[in] vaddr The virtual address of the first byte to use for the heap.
[in] maxpages The maximum number of pages that the heap will grow to fill.
Returns
A pointer to a the created heap structure.
Definition at line 61 of file heap.c.
Referenced by cmd_test_heap().
void heap_destroy (heap_t * heap)
Destroy a heap, returning its memory to page table.
Parameters
[in] heap The heap to be destroyed.
Definition at line 90 of file heap.c.
Referenced by cmd_test_heap().
void* heap_alloc (heap_t * heap, uint64_t size)
Allocate memory from a heap.
Parameters
[in] heap The heap from which to allocate the memory.
[in] size The size, in bytes, of the allocation.
Returns
A pointer to a the allocated memory.
Definition at line 239 of file heap.c.
Referenced by cmd_test_heap().
void heap_free (heap_t * heap, void * ptr)
Free memory previously allocated with heap_alloc.
Parameters
[in] heap The heap from which the memory was allocated.
[in] ptr A pointer to the memory that was allocated.
Definition at line 319 of file heap.c.
Referenced by cmd_test_heap().