MonkOS: /home/brett/c/monk/kernel/mem/map.c File Reference
map.c File Reference
#include <core.h>
#include <libc/string.h>
#include <kernel/x86/cpu.h>
#include <kernel/interrupt/interrupt.h>
#include <kernel/mem/map.h>
#include <kernel/mem/paging.h>
#include <kernel/mem/table.h>
Data Structures
struct kptable_t
Structure used to track the growth of the kernel's page table.
Functions
static uint64_t get_pdflags (uint32_t memtype)
Return flags for large-page leaf entries in level 3 (PDPT) and level 2 (PDT) tables.
static uint64_t get_ptflags (uint32_t memtype)
Return flags for entries in level 1 (PT) tables.
static uint64_t alloc_page ()
static void create_huge_page (uint64_t addr, uint32_t memtype)
static void create_large_page (uint64_t addr, uint32_t memtype)
static void create_small_page (uint64_t addr, uint32_t memtype)
static void map_region (const memtable_t *table, const memregion_t *region)
void map_memory ()
Identity-map all usable physical memory into the kernel page table.
Variables
static kptable_t kptable
Data Structure Documentation
struct kptable_t
Structure used to track the growth of the kernel's page table.
Definition at line 19 of file map.c.
Data Fields
page_t * root The top-level (PML4) page table.
page_t * next_page The next page to use when allocating.
page_t * term_page Just beyond the last available page.
Function Documentation
static uint64_t get_pdflags (uint32_t memtype) static
Return flags for large-page leaf entries in level 3 (PDPT) and level 2 (PDT) tables.
Definition at line 31 of file map.c.
Referenced by create_huge_page(), and create_large_page().
static uint64_t get_ptflags (uint32_t memtype) static
Return flags for entries in level 1 (PT) tables.
Definition at line 50 of file map.c.
Referenced by create_small_page().
static uint64_t alloc_page () inline static
Definition at line 68 of file map.c.
Referenced by create_huge_page(), create_large_page(), and create_small_page().
static void create_huge_page (uint64_t addr, uint32_t memtype) static
Definition at line 76 of file map.c.
Referenced by map_region().
static void create_large_page (uint64_t addr, uint32_t memtype) static
Definition at line 90 of file map.c.
Referenced by map_region().
static void create_small_page (uint64_t addr, uint32_t memtype) static
Definition at line 109 of file map.c.
Referenced by map_region().
static void map_region (const memtable_t * table, const memregion_t * region) static
Definition at line 133 of file map.c.
Referenced by map_memory().
void map_memory ()
Identity-map all usable physical memory into the kernel page table.
Definition at line 175 of file map.c.
Referenced by page_init().
Variable Documentation
kptable_t kptable static
Definition at line 26 of file map.c.