MonkOS: /home/brett/c/monk/kernel/mem/paging.c File Reference
paging.c File Reference
Paged memory management.
#include <core.h>
#include <libc/stdlib.h>
#include <libc/string.h>
#include <kernel/x86/cpu.h>
#include <kernel/interrupt/interrupt.h>
#include <kernel/mem/map.h>
#include <kernel/mem/table.h>
#include <kernel/mem/paging.h>
Data Structures
struct pf_t
The pf structure represents a page frame record, which tracks page frames in the page frame database.
struct context
The log context describes the state of the log buffers.
Macros
#define PAGE_SHIFT 12
#define PAGE_SHIFT_LARGE 21
#define PFN_INVALID ((uint32_t)-1)
#define PADDR_TO_PF(a) ((pf_t *)(pgcontext.pfdb + ((a) >> PAGE_SHIFT)))
#define PF_TO_PADDR(pf) ((uint64_t)((pf) - pgcontext.pfdb) << PAGE_SHIFT)
#define PFN_TO_PF(pfn) ((pf_t *)((pfn) + pgcontext.pfdb))
#define PF_TO_PFN(pf) ((uint32_t)((pf) - pgcontext.pfdb))
#define PTE_TO_PADDR(pte) ((pte) & ~PGMASK_OFFSET)
Enumerations
Functions
STATIC_ASSERT (sizeof(pf_t)==32,"Unexpected page frame size")
static void * reserve_region (const memtable_t *table, uint64_t size, uint32_t alignshift)
Reserve an aligned region of memory managed by the memory table module.
void page_init ()
Initialize the page frame database.
static pf_t * pfalloc ()
static void pffree (pf_t *pf)
static uint64_t pgalloc ()
static void pgfree (uint64_t paddr)
static void pgfree_recurse (page_t *page, int level)
static void add_pte (pagetable_t *pt, uint64_t vaddr, uint64_t paddr, uint32_t pflags)
Add to the page table an entry mapping a virtual address to a physical address.
static uint64_t remove_pte (pagetable_t *pt, uint64_t vaddr)
void pagetable_create (pagetable_t *pt, void *vaddr)
Create a new page table that can be used to associate virtual addresses with physical addresses.
void pagetable_destroy (pagetable_t *pt)
Destroy a page table.
void pagetable_activate (pagetable_t *pt)
Activate a page table on the CPU, so all virtual memory operations are performed relative to the page table.
void * page_alloc (pagetable_t *pt, void *vaddr_in, int count)
Allocate one or more pages contiguous in virtual memory.
void page_free (pagetable_t *pt, void *vaddr_in, int count)
Free one or more contiguous pages from virtual memory.
Variables
static struct context pgcontext
Detailed Description
Paged memory management.
Definition in file paging.c.
Data Structure Documentation
struct pf_t
The pf structure represents a page frame record, which tracks page frames in the page frame database.
Definition at line 43 of file paging.c.
Data Fields
uint32_t prev Prev pfn on available list.
uint32_t next Next pfn on available list.
uint16_t refcount Number of references to this page.
uint16_t sharecount Number of processes sharing page.
uint16_t flags
uint8_t type PFTYPE of page frame.
uint8_t reserved0
uint64_t reserved1
uint64_t reserved2
struct context
The log context describes the state of the log buffers.
The paging context structure holds the state of the paging module.
There are two buffers: the record buffer and the message buffer. The record buffer is a circular queue that contains records describing the most recent 1024 log messages. The message buffer contains the text messages associated with each of the records in the log buffer.
Definition at line 46 of file log.c.
Data Fields
record_t rbuf[RBUFSIZE] Circular record buffer.
int rhead index of oldest record in rbuf
int rtail rbuf index of next record to write
int rbufsz number of records in rbuf
char mbuf[MBUFSIZE] Circular message text buffer.
int mhead index of oldest char in mbuf
int mtail mbuf index of next char to write
int mbufsz the number of characters in mbuf
callback_t callbacks[MAX_CALLBACKS]
int callbacks_size number of registrations
page_t * pagetable The kernel's page table.
pf_t * pfdb Page frame database.
uint32_t pfcount Number of frames in the pfdb.
uint32_t pfavail Available frames in the pfdb;.
uint32_t pfnhead Available frame list head.
uint32_t pfntail Available frame list tail.
Macro Definition Documentation
#define PAGE_SHIFT 12
Definition at line 20 of file paging.c.
Referenced by page_init().
#define PAGE_SHIFT_LARGE 21
Definition at line 21 of file paging.c.
Referenced by page_init().
#define PFN_INVALID ((uint32_t)-1)
Definition at line 24 of file paging.c.
Referenced by page_init(), pfalloc(), and pffree().
#define PADDR_TO_PF (a) ((pf_t *)(pgcontext.pfdb + ((a) >> PAGE_SHIFT)))
Definition at line 27 of file paging.c.
Referenced by pgfree(), and pgfree_recurse().
#define PF_TO_PADDR (pf) ((uint64_t)((pf) - pgcontext.pfdb) << PAGE_SHIFT)
Definition at line 28 of file paging.c.
Referenced by pgalloc().
#define PFN_TO_PF (pfn) ((pf_t *)((pfn) + pgcontext.pfdb))
Definition at line 29 of file paging.c.
Referenced by page_init(), and pfalloc().
#define PF_TO_PFN (pf) ((uint32_t)((pf) - pgcontext.pfdb))
Definition at line 30 of file paging.c.
Referenced by pffree().
#define PTE_TO_PADDR (pte) ((pte) & ~PGMASK_OFFSET)
Definition at line 31 of file paging.c.
Referenced by pgfree_recurse().
Enumeration Type Documentation
anonymous enum
Enumerator
PFTYPE_RESERVED
PFTYPE_AVAILABLE
PFTYPE_ALLOCATED
Definition at line 34 of file paging.c.
Function Documentation
STATIC_ASSERT (sizeof(pf_t) = =32, "Unexpected page frame size")
static void* reserve_region (const memtable_t * table, uint64_t size, uint32_t alignshift) static
Reserve an aligned region of memory managed by the memory table module.
Definition at line 73 of file paging.c.
Referenced by page_init().
void page_init ()
Initialize the page frame database.
The page frame database manages the physical memory used by all memory pages known to the kernel.
Definition at line 102 of file paging.c.
Referenced by kmain().
static pf_t* pfalloc () static
Definition at line 176 of file paging.c.
Referenced by pgalloc().
static void pffree (pf_t * pf) static
Definition at line 199 of file paging.c.
Referenced by pgfree().
static uint64_t pgalloc () static
Definition at line 221 of file paging.c.
Referenced by add_pte(), page_alloc(), and pagetable_create().
static void pgfree (uint64_t paddr) static
Definition at line 235 of file paging.c.
Referenced by page_free(), and pgfree_recurse().
static void pgfree_recurse (page_t * page, int level) static
Definition at line 243 of file paging.c.
Referenced by pagetable_destroy().
static void add_pte (pagetable_t * pt, uint64_t vaddr, uint64_t paddr, uint32_t pflags) static
Add to the page table an entry mapping a virtual address to a physical address.
Definition at line 273 of file paging.c.
Referenced by page_alloc(), and pagetable_create().
static uint64_t remove_pte (pagetable_t * pt, uint64_t vaddr) static
Definition at line 321 of file paging.c.
Referenced by page_free().
void pagetable_create (pagetable_t * pt, void * vaddr)
Create a new page table that can be used to associate virtual addresses with physical addresses.
Parameters
[in] pt A pointer to the pagetable structure that will hold the page table.
[in] vaddr The virtual address within the new page table where the page table will be mapped.
Returns
A handle to the created page table.
Definition at line 344 of file paging.c.
void pagetable_destroy (pagetable_t * pt)
Destroy a page table.
Parameters
[in] pt A handle to the page table to destroy.
Definition at line 355 of file paging.c.
void pagetable_activate (pagetable_t * pt)
Activate a page table on the CPU, so all virtual memory operations are performed relative to the page table.
Parameters
[in] pt A handle to the activated page table.
Definition at line 367 of file paging.c.
void* page_alloc (pagetable_t * pt, void * vaddr, int count)
Allocate one or more pages contiguous in virtual memory.
Parameters
[in] pt Handle to the page table from which to allocate the page(s).
[in] vaddr The virtual address of the first allocated page.
[in] count The number of contiguous virtual memory pages to allocate.
Returns
A virtual memory pointer to the first page allocated.
Definition at line 377 of file paging.c.
void page_free (pagetable_t * pt, void * vaddr, int count)
Free one or more contiguous pages from virtual memory.
Parameters
[in] pt Handle to ehte page table from which to free the page(s).
[in] vaddr The virtual address of the first allocated page.
[in] count The number of contiguous virtual memory pages to free.
Definition at line 387 of file paging.c.
Variable Documentation
struct context pgcontext static
Definition at line 69 of file paging.c.
Referenced by page_init(), pfalloc(), and pffree().