MonkOS: /home/brett/c/monk/kernel/shell.c File Reference
shell.c File Reference
Simple kernel shell for testing purposes.
#include <core.h>
#include <libc/stdio.h>
#include <libc/stdlib.h>
#include <libc/string.h>
#include <kernel/device/pci.h>
#include <kernel/device/tty.h>
#include <kernel/device/keyboard.h>
#include <kernel/mem/acpi.h>
#include <kernel/x86/cpu.h>
Data Structures
struct mode_t
Shell mode descriptor.
struct cmd
A command descriptor, describing each command accepted in command mode.
Macros
#define TTY_CONSOLE 0
Functions
static void command_prompt ()
static void command_run ()
static void keycode_run ()
static bool cmd_display_help ()
static bool cmd_display_apic ()
static bool cmd_display_pci ()
static bool cmd_display_pcie ()
static bool cmd_switch_to_keycodes ()
static void switch_mode (mode_t *mode)
static int cmp_cmds (const void *c1, const void *c2)
static bool command_exec (const char *cmd)
void kshell ()
Variables
static mode_t mode_command
static mode_t mode_keycode
static mode_t * active_mode
static struct cmd commands []
Detailed Description
Simple kernel shell for testing purposes.
Definition in file shell.c.
Macro Definition Documentation
#define TTY_CONSOLE 0
Definition at line 20 of file shell.c.
Referenced by cmd_display_apic(), cmd_display_help(), cmd_display_pcie(), cmd_switch_to_keycodes(), command_exec(), command_prompt(), command_run(), and keycode_run().
Function Documentation
static void command_prompt () static
Definition at line 196 of file shell.c.
Referenced by command_run().
static void command_run () static
Definition at line 202 of file shell.c.
static void keycode_run () static
Definition at line 254 of file shell.c.
static bool cmd_display_help () static
Definition at line 96 of file shell.c.
static bool cmd_display_apic () static
Definition at line 109 of file shell.c.
static bool cmd_display_pci () static
Definition at line 146 of file shell.c.
static bool cmd_display_pcie () static
Definition at line 153 of file shell.c.
static bool cmd_switch_to_keycodes () static
Definition at line 172 of file shell.c.
static void switch_mode (mode_t * mode) static
Definition at line 59 of file shell.c.
Referenced by cmd_switch_to_keycodes(), and keycode_run().
static int cmp_cmds (const void * c1, const void * c2) static
Definition at line 89 of file shell.c.
Referenced by kshell().
static bool command_exec (const char * cmd) static
Definition at line 181 of file shell.c.
Referenced by command_run().
void kshell ()
Definition at line 289 of file shell.c.
Referenced by kmain().
Variable Documentation
mode_t mode_command static
Initial value:
=
{
    command_prompt,
    command_run,
    NULL
}
Definition at line 41 of file shell.c.
Referenced by kshell().
mode_t mode_keycode static
Initial value:
=
{
    NULL,
    keycode_run,
    NULL
}
Definition at line 49 of file shell.c.
mode_t* active_mode static
Definition at line 56 of file shell.c.
struct cmd commands[] static
Initial value:
=
{
    { "?", NULL, cmd_display_help },
    { "help", "Show this help text", cmd_display_help },
    { "apic", "Show APIC configuration", cmd_display_apic },
    { "pci", "Show PCI devices", cmd_display_pci },
    { "pcie", "Show PCIexpress configuration", cmd_display_pcie },
    { "kc", "Switch to keycode display mode", cmd_switch_to_keycodes },
}
Definition at line 78 of file shell.c.