MonkOS: mode_t Struct Reference
mode_t Struct Reference
Shell mode descriptor.
Data Fields
void(* start)()
void(* run)()
void(* stop)()
Detailed Description
Shell mode descriptor.
Definition at line 33 of file shell.c.
Field Documentation
void(* mode_t::start) ()
Definition at line 35 of file shell.c.
Referenced by kshell(), and switch_mode().
void(* mode_t::run) ()
Definition at line 36 of file shell.c.
Referenced by kshell().
void(* mode_t::stop) ()
Definition at line 37 of file shell.c.
Referenced by switch_mode().
The documentation for this struct was generated from the following file:
/home/brett/c/monk/kernel/shell.c