MonkOS: /home/brett/c/monk/include/kernel/mem/table.h File Reference
table.h File Reference
Physical memory table describing usable and reserved regions of physical memory.
#include <core.h>
Data Structures
struct memregion_t
A memregion represents and describes a contiguous region of physical memory.
struct memtable_t
A memory table describing available and reserved regions of physical memory.
Enumerations
Functions
void memtable_init ()
Initialize the memory table using information provided by the BIOS during boot loading.
void memtable_add (uint64_t addr, uint64_t size, enum memtype type)
Add a region of memory to the memory table.
const memtable_t * memtable ()
Return a pointer to the current memory table.
Detailed Description
Physical memory table describing usable and reserved regions of physical memory.
Most of the table is derived from data provided by the system BIOS at boot time.
Definition in file table.h.
Data Structure Documentation
struct memregion
A memregion represents and describes a contiguous region of physical memory.
Definition at line 37 of file table.h.
Data Fields
uint64_t addr base address
uint64_t size size of memory region
int32_t type Memory type (see memtype enum)
uint32_t flags flags (currently unused)
struct memtable
A memory table describing available and reserved regions of physical memory.
There are no gaps in a memory table.
Definition at line 52 of file table.h.
Data Fields
uint64_t count Memory regions in the table.
uint64_t last_usable End of last usable region.
memregion_t region[1] An array of 'count' memory regions.
Enumeration Type Documentation
enum memtype
The types of physical memory.
Enumerator
MEMTYPE_USABLE
Reported usable by the BIOS.
MEMTYPE_RESERVED
Reported (or inferred) to be reserved.
MEMTYPE_ACPI
Used for ACPI tables or code.
MEMTYPE_ACPI_NVS
Used for ACPI non-volatile storage.
MEMTYPE_BAD
Reported as bad memory.
MEMTYPE_UNCACHED
Marked as uncacheable, usually for I/O.
MEMTYPE_UNMAPPED
Marked as "do not map".
Definition at line 21 of file table.h.
Function Documentation
void memtable_init ()
Initialize the memory table using information provided by the BIOS during boot loading.
Definition at line 295 of file table.c.
Referenced by kmain().
void memtable_add (uint64_t addr, uint64_t size, enum memtype type)
Add a region of memory to the memory table.
Parameters
[in] addr The starting address of the region.
[in] size The size of the region.
[in] type The type of memory to add.
Definition at line 321 of file table.c.
Referenced by acpi_init(), map_table(), and reserve_region().
const memtable_t* memtable ()
Return a pointer to the current memory table.
Returns
A pointer to the memory table.
Definition at line 315 of file table.c.
Referenced by map_memory(), and page_init().