MonkOS: /home/brett/c/monk/kernel/mem/table.c File Reference
table.c File Reference
Physical memory table describing usable and reserved regions of physical memory.
#include <core.h>
#include <libc/stdlib.h>
#include <libc/string.h>
#include <kernel/mem/map.h>
#include <kernel/mem/table.h>
Functions
static void add_region (uint64_t addr, uint64_t size, enum memtype type)
Add a memory region to the end of the memory table.
static int cmp_region (const void *a, const void *b)
Compare two memory region records and return a sorting integer.
static void collapse (memregion_t *r, memregion_t *term)
Remove a region from the memory table and shift all subsequent regions down by one.
static void insertafter (memregion_t *r, memregion_t *term)
Insert a new, uninitialized memory region record after an existing record in the memory table.
static void resort (memregion_t *r, memregion_t *term)
Re-sort all unsorted region records starting from the requested record.
static void collapse_overlaps ()
Find all overlapping memory regions in the memory table and collapse or reorganize them.
static void fill_gaps (int32_t type)
Find missing memory regions in the table, and fill them with entries of the requested type.
static void consolidate_neighbors ()
Find adjacent memory entries of the same type and merge them.
static void update_last_usable ()
static void normalize ()
void memtable_init ()
Initialize the memory table using information provided by the BIOS during boot loading.
const memtable_t * memtable ()
Return a pointer to the current memory table.
void memtable_add (uint64_t addr, uint64_t size, enum memtype type)
Add a region of memory to the memory table.
Variables
static memtable_t * table = (memtable_t *)MEM_TABLE_BIOS
static bool initialized = false
Detailed Description
Physical memory table describing usable and reserved regions of physical memory.
Most of the table is derived from data provided by the system BIOS at boot time.
Definition in file table.c.
Function Documentation
static void add_region (uint64_t addr, uint64_t size, enum memtype type) static
Add a memory region to the end of the memory table.
Definition at line 25 of file table.c.
Referenced by memtable_add(), and memtable_init().
static int cmp_region (const void * a, const void * b) static
Compare two memory region records and return a sorting integer.
Definition at line 38 of file table.c.
Referenced by normalize(), and resort().
static void collapse (memregion_t * r, memregion_t * term) inline static
Remove a region from the memory table and shift all subsequent regions down by one.
Definition at line 56 of file table.c.
Referenced by collapse_overlaps(), and consolidate_neighbors().
static void insertafter (memregion_t * r, memregion_t * term) inline static
Insert a new, uninitialized memory region record after an existing record in the memory table.
Definition at line 66 of file table.c.
Referenced by collapse_overlaps(), and fill_gaps().
static void resort (memregion_t * r, memregion_t * term) static
Re-sort all unsorted region records starting from the requested record.
Definition at line 75 of file table.c.
Referenced by collapse_overlaps().
static void collapse_overlaps () static
Find all overlapping memory regions in the memory table and collapse or reorganize them.
Definition at line 90 of file table.c.
Referenced by normalize().
static void fill_gaps (int32_t type) static
Find missing memory regions in the table, and fill them with entries of the requested type.
Definition at line 204 of file table.c.
Referenced by normalize().
static void consolidate_neighbors () static
Find adjacent memory entries of the same type and merge them.
Definition at line 244 of file table.c.
Referenced by normalize().
static void update_last_usable () static
Definition at line 262 of file table.c.
Referenced by normalize().
static void normalize () static
Definition at line 275 of file table.c.
Referenced by memtable_add(), and memtable_init().
void memtable_init ()
Initialize the memory table using information provided by the BIOS during boot loading.
Definition at line 295 of file table.c.
Referenced by kmain().
const memtable_t* memtable ()
Return a pointer to the current memory table.
Returns
A pointer to the memory table.
Definition at line 315 of file table.c.
Referenced by map_memory(), and page_init().
void memtable_add (uint64_t addr, uint64_t size, enum memtype type)
Add a region of memory to the memory table.
Parameters
[in] addr The starting address of the region.
[in] size The size of the region.
[in] type The type of memory to add.
Definition at line 321 of file table.c.
Referenced by acpi_init(), map_table(), and reserve_region().
Variable Documentation
memtable_t* table = (memtable_t *)MEM_TABLE_BIOS static
Definition at line 20 of file table.c.
Referenced by add_region(), collapse(), collapse_overlaps(), consolidate_neighbors(), fill_gaps(), insertafter(), map_memory(), memtable(), normalize(), page_init(), and update_last_usable().
bool initialized = false static
Definition at line 21 of file table.c.
Referenced by memtable_add(), and memtable_init().